version: '3'

services:
  app:
    build: .
    ports:
      - 3001:3000
      - 5556:5555
    volumes:
      - .:/home/node/app
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

    # depends_on:
    #   - db

    # não use docker desktop (linux) ou (windows)

    # db:
    #   image: bitnami/mongodb:5.0.17
    #   platform: linux/amd64
    #   volumes:
    #     - mongodb_data:/bitnami/mongodb
    #   ports:
    #     - '27017:27017'
    #   environment:
    #     MONGODB_ROOT_PASSWORD: root
    #     MONGODB_REPLICA_SET_MODE: primary
    #     MONGODB_REPLICA_SET_KEY: 123456
    #     MONGODB_DATABASE: nest
#   db:
#     build: ./.docker/mongo
#     environment:
#       MONGO_INITDB_ROOT_PASSWORD: root
#       MONGO_REPLICA_HOST: db
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:
#     driver: local

# networks:
#   my-network:
#     external: true
# //Linux ou Mac
# /etc/hosts

# 127.0.0.1 host.docker.internal

# //Windows
# C:\Windows\system32\drivers\etc\hosts (bloco de notas como administrador)
# 127.0.0.1 host.docker.internal
