import { z } from 'zod';

export const STATUS_CONTRATO_REGEX =
  /ATIVO|INATIVO|PENDENTE|APROVADO|REJEITADO|SUSPENSO|VENCIDO|CANCELADO|QUITADO|NOVA_CONSIGNACAO/;

export const STATUS_OPERACAO_REGEX =
  /AGUARDANDO_CONFIRMACAO|CONFIRMADO|CANCELADO|LIBERADA|UTILIZADO|ENVIADA_SERVIDOR|ENVIADA_CONSIGNATARIA|CANCELADA_SERVIDOR|CANCELADA_CONSIGNATARIA|APROVADA_SERVIDOR|APROVADA_CONSIGNATARIA/;

export const STATUS_BAIXA_REGEX =
  /ABERTA|BAIXADA|CANCELADA|PAGA|VENCIDA|PROTESTADA|SUSPENSA|ATRASADA|PENDENTE|ENVIADA|RECEBIDA|ENVIADA_BANCO|RECEBIDA_BANCO|PROTESTADA_BANCO|CANCELADA_BANCO|PAGA_BANCO|VENCIDA_BANCO|SUSPENSA_BANCO|ATRASADA_BANCO/;

export const STATUS_MARGEM_REGEX =
  /AGUARDANDO_LIBERACAO|BLOQUEADA|LIBERADA|SUSPENSA|CANCELADA/;
